/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 213 "/usr/lib/gcc/x86_64-linux-gnu/4.7/include/stddef.h"
typedef unsigned long size_t;
#line 3 "test_field.c"
struct sock {
   int *array ;
   int b ;
   char c ;
};
#line 471 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
#line 8 "test_field.c"
int recv(struct sock *socket ) 
{ 


  {
#line 9
  socket->b = 0;
#line 10
  socket->c = (char)100;
#line 11
  return ((int )socket->c);
}
}
#line 13 "test_field.c"
int main(void) 
{ 
  struct sock *socket ;
  void *tmp ;
  void *tmp___0 ;

  {
#line 15
  tmp = malloc(sizeof(struct sock *));
#line 15
  socket = (struct sock *)tmp;
#line 16
  tmp___0 = malloc(sizeof(int [10]));
#line 16
  socket->array = (int *)tmp___0;
#line 17
  recv(socket);
#line 18
  return (0);
}
}
